association-gorilla/doswitch-2

.rubocop.yml, .rubocop_todo.yml, Gemfile, app/controllers/application_controller.rb, app/controllers/verbs_controller.rb, app/helpers/verbs_helper.rb, app/models/verb.rb, app/views/verbs/edit.html.erb, config/routes.rb, spec/requests/achieve_rates_request_spec.rb, spec/requests/actions_request_spec.rb, spec/requests/homes_request_spec.rb, spec/requests/notifications_request_spec.rb, spec/requests/plan_allots_request_spec.rb, spec/requests/real_allots_request_spec.rb, spec/requests/rewards_request_spec.rb, spec/requests/users_request_spec.rb, spec/requests/verbs_request_spec.rb
・importantとselectedの変更機能追加
・変更ロジックはmodelに記述
・変更ボタンはヘルパーに記述
・rubocopによる自動修正
=> verb status turn #3

app/controllers/verbs_controller.rb, app/helpers/verbs_helper.rb, app/models/verb.rb, app/views/verbs/edit.html.erb
・優先アクションを１〜３になるように設定
・優先ではない設定アクションを１〜３になるように設定
・許容範囲から外れる場合はボタンを表示しないようにする
=> add_verb_status_check #3

.rubocop_todo.yml, Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/controllers/homes_controller.rb, app/helpers/homes_helper.rb, app/models/achieve_rate.rb, app/models/detail_plan_allot.rb, app/models/detail_real_allot.rb, app/models/notification.rb, app/models/plan_allot.rb, app/models/real_allot.rb, app/models/reward.rb, app/models/user.rb, app/models/verb.rb, app/views/homes/top.html.erb, config/routes.rb, db/migrate/20200517124601_create_achieve_rates.rb, db/migrate/20200517124615_create_notifications.rb, db/migrate/20200517124657_create_plan_allots.rb, db/migrate/20200517124704_create_real_allots.rb, db/migrate/20200518095225_create_detail_real_allots.rb, db/migrate/20200518095248_create_detail_plan_allots.rb, db/schema.rb
・実行した行動時間の総記録機能
・実行した行動時間の詳細記録機能
・実行時間がリアルタイムで変動するように画面に表示
・ヘルパーにロジックを格納
・アソシエーショ設定
=> add action_record_function #4

app/controllers/homes_controller.rb, app/controllers/verbs_controller.rb, app/helpers/homes_helper.rb, app/models/detail_real_allot.rb, app/models/real_allot.rb, app/views/homes/top.html.erb
他のアクションにも、スタート・ストップボタンを付ける
他のスタートボタンを押したときにいま動いているアクションを止める
画面を更新したときに測定を保存して再スタート
コントローラーのビジネスロジックをモデルにリファクタリング
=> add other_action_relevant #11

app/helpers/homes_helper.rb, app/models/detail_real_allot.rb, app/models/real_allot.rb, config/application.rb, lib/tasks/action_restart.rake
・タイムゾーンでTokyoを指定して時刻を取得
・0時の定時処理時にreal_allotレコードを作成追加
=> add time_zone #12

app/helpers/homes_helper.rb, app/models/real_allot.rb, db/migrate/20200517124657_create_plan_allots.rb, db/migrate/20200517124704_create_real_allots.rb, db/schema.rb, lib/tasks/action_restart.rake
=> add real_allot user_id #21

app/controllers/users/registrations_controller.rb, config/routes.rb
・サインアップ後に行動（「学習」、「休憩」、「その他」）をデフォルトで作成
=> add after_signup_verb_create #26

app/controllers/verbs_controller.rb, app/helpers/verbs_helper.rb, app/views/verbs/index.html.erb, config/routes.rb
=> add verb_create #28

app/helpers/verbs_helper.rb, config/schedule.rb, lib/tasks/achieve_record.rake
=> fix achieve_record_create #21

app/controllers/plan_allots_controller.rb, app/models/plan_allot.rb, app/views/layouts/application.html.erb, app/views/plan_allots/index.html.erb, app/views/users/edit.html.erb, app/views/verbs/index.html.erb, config/initializers/application_controller_renderer.rb, config/routes.rb, db/migrate/20200517124240_devise_create_users.rb, db/migrate/20200517124657_create_plan_allots.rb, db/schema.rb
・学習計画のCRUD機能追加
・indexページに「本日の計画」「計画の追加」を用意
・plan_allotカラムのallotをallot_hとallot_mに変更
・plan_allotカラムのtermをbegin_termとend_termに変更
=> add plan_allot_CRUD #22

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/controllers/plan_allots_controller.rb, app/models/plan_allot.rb, app/views/layouts/application.html.erb, app/views/plan_allots/index.html.erb, app/views/plan_allots/index.json.jbuilder, db/migrate/20200517124657_create_plan_allots.rb, db/migrate/20200517124704_create_real_allots.rb, db/schema.rb
・カレンダーを計画設定ページに追加
・イベントを表示機能追加
=> add plan_calendar #33

app/assets/javascripts/application.js, app/controllers/plan_allots_controller.rb, app/views/plan_allots/index.json.jbuilder, app/views/plan_allots/lists.html.erb, config/routes.rb
=> add plan_lists #38

app/helpers/homes_helper.rb, app/models/detail_real_allot.rb, app/views/homes/top.html.erb, app/views/plan_allots/index.json.jbuilder
- 設定した計画をトップ画面で確認できるように設定
- 計画設定画面で何時間行う計画かを確認できるように設定
=> add plan_time_insight

app/assets/stylesheets/homes.scss, app/helpers/homes_helper.rb, app/views/homes/top.html.erb, app/views/layouts/application.html.erb, app/views/plan_allots/index.json.jbuilder
・トップページに00:00:00形式で表示
・目標達成していたらチェックマークが黄緑色になるように設定
=> add achieve_check #34

app/helpers/homes_helper.rb
=> add plan_clear_status #34

.rubocop_todo.yml, app/assets/stylesheets/application.scss, app/assets/stylesheets/homes.scss, app/assets/stylesheets/users.scss, app/helpers/homes_helper.rb, app/views/homes/top.html.erb
・ヘルパー内でボタンをリンクタグで囲むためにdivタグを試験的に設置
=> add helper_divtag #45

app/controllers/achieve_records_controller.rb, app/helpers/achieve_records_helper.rb, app/views/achieve_records/show.html.erb, lib/tasks/achieve_record.rake
=> add plan_compare #34

app/assets/javascripts/homes.js, app/assets/stylesheets/homes.scss, app/views/homes/top.html.erb
=> [Add]スイッチ押した時のアクション

app/assets/javascripts/homes.js, app/assets/stylesheets/homes.scss, app/views/homes/top.html.erb
トップページにあるスイッチのスタンド作りました！スイッチっぽくなったよ〜
=> [Add]スイッチスタンド胴体,[Modified]is-activeクラスセレクタ変更

app/assets/javascripts/application.js, app/assets/javascripts/homes.js, app/controllers/plan_allots_controller.rb, app/helpers/homes_helper.rb, app/views/achieve_records/index.html.erb, app/views/homes/top.html.erb, app/views/plan_allots/index.html.erb, app/views/plan_allots/lists.html.erb, db/migrate/20200517124657_create_plan_allots.rb, db/schema.rb
・計画に対してのご褒美とペナルティの設定フォーム
・CRUD機能
・ご褒美とペナルティカラムをPlanAllotテーブルに追加して、Rewardテーブルを削除することに変更
=> [Add]ご褒美とペナルティの設定フォーム #23

app/assets/stylesheets/homes.scss, app/views/homes/top.html.erb, db/schema.rb, ubuntu-bionic-18.04-cloudimg-console.log
最優先の方のスイッチ追加しました。
データベースアップデートしました。
jsの記述はそのままです。
=> Prioritize switch

app/assets/stylesheets/application.scss, app/views/achieve_records/index.html.erb, app/views/achieve_records/show.html.erb, app/views/homes/about.html.erb, app/views/homes/top.html.erb, app/views/layouts/_nav.html.erb, app/views/plan_allots/index.html.erb, app/views/plan_allots/lists.html.erb, app/views/users/edit.html.erb, app/views/verbs/index.html.erb
メニューナビを部分テンプレート(_nav.html.erb)にして全画面に貼り付けました。
ナビのhtml,cssも変更しました
=> Partial nav

app/views/layouts/_nav.html.erb
インデント４マス→２マス
抜けていた＜/div＞を付け足しました
=> [Modified]ページインデント２マス

app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/homes.scss, app/helpers/homes_helper.rb, app/views/achieve_records/index.html.erb, app/views/homes/_prioritize_action.html.erb, app/views/homes/_setup_action.html.erb, app/views/homes/top.html.erb, app/views/layouts/_nav.html.erb
・計測タイマーをスイッチに重ねてタイマーっぽくしたしました。うーんちょっと微妙！
CSSいじりたいんだけどRailsと絡んでて
稼働してるときのJSヘルパーの仕組みを今度教えて欲しい！
[homes.helper.rbとapplication.js]
タイマー表示に絡む部分を少し変えました。
目標時間の方もなんとかできればと思います。
・_nav.html.erbコードずれてたから整えました。
・bootstrap4によるトップページのレイアウト崩れ直しました。
=> Current timer layout

app/views/plan_allots/lists.html.erb
・条件分岐のRewardをPlanAllotに変更
・ローカル変数を使用してリファクタリング
=> [Fix]Rewardデータベース削除後の変更忘れ修正

.rubocop_todo.yml, app/helpers/homes_helper.rb
目標の設定時間に関係なく、表示されるようになっていたため
今日の日付が該当目標の時刻範囲に入っていれば表示するように修正
=> [fix]目標表示タイミング修正
